name: Run Python Script

on:
  push:
    branches:
      - master  # Укажите ветку, на которую будут реагировать

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: |
        python main.py

 - name: Check created files
  run: |
    echo "Checking for files"
    ls -al
    cat test_file.txt || echo "Test file not found"