name: Run Python Script

on:
  schedule:
    - cron: '*/5 * * * *'  # Запуск каждые 5 минут

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check Chrome version
      run: google-chrome --version

    - name: Check ChromeDriver version
      run: chromedriver --version

    - name: Run Python script
      run: |
        python main.py

    - name: Check created files
      run: |
        echo "Checking for files"
        ls -al
        cat script_log.txt || echo "Log file not found"
        cat flight_prices.txt || echo "Data file not found"
